AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: File Whitelisting Interface - Lambda Functions Infrastructure

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
  
  DynamoDBTableName:
    Type: String
    Default: file-whitelist-codes
    Description: DynamoDB table name for storing codes
  
  S3BucketName:
    Type: String
    Description: S3 bucket name for file uploads
  
  KMSKeyId:
    Type: String
    Default: ''
    Description: KMS key ID for code signing (optional, leave empty for HMAC)
  
  UseKMS:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Use KMS for signing instead of HMAC
  
  HMACSecret:
    Type: String
    NoEcho: true
    Default: ''
    Description: HMAC secret key (required if UseKMS is false)

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
        USE_KMS: !Ref UseKMS
        CODE_EXPIRY_MINUTES: '60'

Resources:
  # DynamoDB Table
  CodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # KMS Key (optional, if not provided externally)
  SigningKey:
    Type: AWS::KMS::Key
    Condition: CreateKMSKey
    Properties:
      Description: KMS key for code signing
      KeyUsage: SIGN_VERIFY
      KeySpec: RSA_2048
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow Lambda Functions
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - kms:Sign
              - kms:Verify
            Resource: '*'

  SigningKeyAlias:
    Type: AWS::KMS::Alias
    Condition: CreateKMSKey
    Properties:
      AliasName: !Sub 'alias/file-whitelist-signing-${Environment}'
      TargetKeyId: !Ref SigningKey

  # S3 Bucket
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 30

  # IAM Role for Lambda Functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'FileWhitelistLambdaRole-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource: !GetAtt CodesTable.Arn
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:PutObjectAcl
                Resource: !Sub '${UploadBucket}/*'
        - PolicyName: KMSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Sign
                  - kms:Verify
                  - kms:DescribeKey
                Resource: !If
                  - CreateKMSKey
                  - !GetAtt SigningKey.Arn
                  - !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSKeyId}'

  # Code Generator Lambda
  CodeGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'file-whitelist-code-generator-${Environment}'
      CodeUri: code_generator/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
          USE_KMS: !Ref UseKMS
          KMS_KEY_ID: !If
            - CreateKMSKey
            - !GetAtt SigningKey.Arn
            - !Ref KMSKeyId
          HMAC_SECRET: !Ref HMACSecret
          CODE_EXPIRY_MINUTES: '60'
      Events:
        GenerateCode:
          Type: Api
          Properties:
            Path: /generate-code
            Method: post

  # Authorizer Lambda
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'file-whitelist-authorizer-${Environment}'
      CodeUri: authorizer/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
          USE_KMS: !Ref UseKMS
          KMS_KEY_ID: !If
            - CreateKMSKey
            - !GetAtt SigningKey.Arn
            - !Ref KMSKeyId
          HMAC_SECRET: !Ref HMACSecret
      Events:
        ValidateCode:
          Type: Api
          Properties:
            Path: /validate-code
            Method: post

  # Presign URL Lambda
  PresignURLFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'file-whitelist-presign-url-${Environment}'
      CodeUri: presign_url/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          PRESIGNED_URL_EXPIRY_SECONDS: '3600'
          ALLOWED_CONTENT_TYPES: '*/*'
          MAX_FILE_SIZE_MB: '100'
      Events:
        GetPresignedURL:
          Type: Api
          Properties:
            Path: /presign-url
            Method: post
            Auth:
              Authorizer: TokenAuthorizer
        TokenAuthorizer:
          Type: Token
          Properties:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Header: Authorization
              ReauthorizeEvery: 300

Conditions:
  CreateKMSKey: !Equals [!Ref UseKMS, 'true']

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
  
  CodeGeneratorUrl:
    Description: Code Generator endpoint
    Value: !Sub '${ApiGatewayUrl}/generate-code'
  
  PresignURLUrl:
    Description: Presign URL endpoint (requires authorization)
    Value: !Sub '${ApiGatewayUrl}/presign-url'
  
  DynamoDBTableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt CodesTable.Arn
  
  S3BucketName:
    Description: S3 bucket name for uploads
    Value: !Ref S3BucketName
  
  KMSKeyArn:
    Description: KMS key ARN (if created)
    Condition: CreateKMSKey
    Value: !GetAtt SigningKey.Arn

